name: build

on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Export env vars
        run: buildscripts/include/ci.sh export >>$GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: gh-cache/
          key: "${{ env.CACHE_IDENTIFIER }}"
          enableCrossOsArchive: true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install autoconf pkg-config libtool ninja-build python3-pip
          sudo pip3 install meson

      # ✅ DÜZELTME 1: Android 15 uyumlu SDK kurulumu
      - name: Setup Android SDK for Android 15
        run: |
          # Android SDK 35 (Android 15) kurulumu
          echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-35"
          echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
          echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "ndk;27.0.12077973"
          
          # Çevre değişkenlerini ayarla
          echo "ANDROID_COMPILE_SDK=35" >> $GITHUB_ENV
          echo "ANDROID_TARGET_SDK=35" >> $GITHUB_ENV
          echo "ANDROID_MIN_SDK=21" >> $GITHUB_ENV
          echo "ANDROID_NDK_VERSION=27.0.12077973" >> $GITHUB_ENV

      # ✅ DÜZELTME 2: Gradle properties'i önceden ayarla
      - name: Configure Gradle Properties
        run: |
          cat >> gradle.properties << EOF
          android.compileSdk=35
          android.targetSdk=35
          android.buildTools=34.0.0
          android.useAndroidX=true
          android.enableJetifier=true
          org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
          EOF

      - name: Download deps
        run: |
          mkdir -p "$CACHE_FOLDER"
          buildscripts/include/ci.sh install
        env:
          CACHE_MODE: "folder"
          CACHE_FOLDER: "${{ github.workspace }}/gh-cache"

      # ✅ DÜZELTME 3: Temiz build süreci
      - name: Build with Android 15 support
        run: |
          buildscripts/include/ci.sh build
        env:
          ANDROID_COMPILE_SDK: 35
          ANDROID_TARGET_SDK: 35
          ANDROID_NDK_VERSION: 27.0.12077973

      # Universal APK (tüm mimarileri içeren) - Android 15 uyumlu
      - uses: actions/upload-artifact@v4
        with:
          name: mpv-android-universal-android15
          path: app/build/outputs/apk/default/debug/app-default-universal-debug.apk

      # Tüm mimari-spesifik APK'lar - Android 15 uyumlu
      - uses: actions/upload-artifact@v4
        with:
          name: mpv-android-all-architectures-android15
          path: app/build/outputs/apk/default/debug/app-default-*-debug.apk

      # Her mimari için ayrı artifact - Android 15 uyumlu
      - uses: actions/upload-artifact@v4
        with:
          name: mpv-android-armeabi-v7a-android15
          path: app/build/outputs/apk/default/debug/app-default-armeabi-v7a-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: mpv-android-arm64-v8a-android15
          path: app/build/outputs/apk/default/debug/app-default-arm64-v8a-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: mpv-android-x86-android15
          path: app/build/outputs/apk/default/debug/app-default-x86-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: mpv-android-x86_64-android15
          path: app/build/outputs/apk/default/debug/app-default-x86_64-debug.apk

      # ✅ DÜZELTME 4: Release build'i daha güvenilir hale getir
      - name: Build Release APKs
        run: |
          ./gradlew assembleDefaultRelease
        continue-on-error: true
        env:
          ANDROID_COMPILE_SDK: 35
          ANDROID_TARGET_SDK: 35

      - uses: actions/upload-artifact@v4
        with:
          name: mpv-android-release-android15
          path: app/build/outputs/apk/default/release/app-default-*-release.apk
        if: success()
